In [1]:
import os
import re
import random
import numpy as np
import torch
import time
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from tqdm.notebook import tqdm

from data_utils_load import *
from stgcn import STGCN

device = torch.device('cuda:1' if torch.cuda.is_available() else 'cpu')

def filter_valid_files(file_list):
    valid_files = []
    for file in file_list:
        file = file.strip()
        if re.match(r'^ID\d+_\d+\.csv$', file):
            valid_files.append(file)
    return valid_files

def set_deterministic(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

bsize = 64

## Loading Data

In [2]:
save_dir = 'data'
loaded_dir = 'csv_r'
# preprocess_and_save_data(loaded_dir, save_dir)
all_files = filter_valid_files(os.listdir(loaded_dir))
participant_ids = sorted({re.search(r'ID(\d+)_', f).group(1) for f in all_files}, key=lambda x: int(x))

## Gait Unit Creation

In [3]:
class GaitUnitsDataset(Dataset):
    def __init__(self, x_load_list, y_batch, N_gaits):
        self.unit_samples = []
        self.unit_labels = []
        
        for x_task, y_task in zip(x_load_list, y_batch):
            L = x_task.size(0)
            num_units = L - N_gaits + 1
            units = [x_task[start:start + N_gaits] for start in range(num_units)]
            self.unit_samples.extend(units)
            self.unit_labels.extend([y_task] * num_units)
        print(f"Created {len(self.unit_samples)} gait windows")
    
    def __len__(self):
        return len(self.unit_samples)
    
    def __getitem__(self, idx):
        return self.unit_samples[idx], self.unit_labels[idx]


def create_gait_units_dataloader(x_load_list, y_batch, N_gaits, batch_size=64, shuffle=True):
    dataset = GaitUnitsDataset(x_load_list, y_batch, N_gaits)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

## Evaluation Function

In [4]:
def evaluate_model(model, test_loader, n_select_gaits):

    model.eval()
    device = next(model.parameters()).device

    t = []
    p = []

    with torch.no_grad():
        for batch in test_loader:
            if len(batch) == 3:
                x_load_list, y_batch, _ = batch
            else:
                x_load_list, y_batch = batch

            for i, x_load_sample in enumerate(x_load_list):
                x_task = x_load_sample[:6]
                num_units = len(x_task) - n_select_gaits + 1

                unit_preds = []
                    
                for start_idx in range(num_units):
                    unit = x_task[start_idx:start_idx + n_select_gaits]
                    unit_tensor = unit.unsqueeze(0).to(device)
                    y_target = y_batch[i:i+1].to(device)
                        
                    y_pred = model(unit_tensor)
                    unit_preds.append(y_pred.item())

                participant_target = y_target.item()
                participant_pred = float(np.median(np.array(unit_preds)))

                t.append(participant_target)
                p.append(participant_pred)
    
    return t, p

## Model Training Function

In [5]:
def train_model(model, train_loader, experiment_seed=42, num_epochs=1000, N_gaits=2, val_loader=None, patience=50):
    set_deterministic(experiment_seed)
    random.seed(experiment_seed)
    np.random.seed(experiment_seed)

    all_x = []
    all_y = []
    
    for batch in train_loader:
        if len(batch) == 3:
            x_load_list, y_batch, _ = batch
        else:
            x_load_list, y_batch = batch
        all_x.extend(x_load_list)
        all_y.extend(y_batch)
    
    optimized_train_loader = create_gait_units_dataloader(all_x, all_y, N_gaits=N_gaits, 
                                                          batch_size=bsize, shuffle=True)
    
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs)

    best_val_mae = float('inf')
    best_state = None
    epochs_no_improve = 0

    print("Starting training...")
    for epoch in range(num_epochs):
        model.train()
        total_loss = 0
        
        for x_batch, y_batch in optimized_train_loader:
            x_batch = x_batch.to(device) 
            y_batch = y_batch.to(device)  
            
            y_pred = model(x_batch).view(-1)
            loss = F.l1_loss(y_pred, y_batch)
            
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        
        scheduler.step()

        if val_loader is not None:
            val_t, val_p = evaluate_model(model, val_loader, n_select_gaits=N_gaits)
            val_mae = np.mean(np.abs(np.array(val_t) - np.array(val_p)))
            if val_mae < best_val_mae:
                best_val_mae = val_mae
                best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                epochs_no_improve = 0
            else:
                epochs_no_improve += 1
            if epochs_no_improve >= patience:
                print(f"Early stopping at epoch {epoch + 1} (no improvement for {patience} epochs)")
                if best_state is not None:
                    model.load_state_dict(best_state)
                break
        
        if (epoch + 1) % 100 == 0:
            avg_loss = total_loss / len(optimized_train_loader)
            msg = f"[Epoch {epoch + 1}/{num_epochs}] Train MAE: {avg_loss:.4f}"
            if val_loader is not None:
                msg += f" | Val MAE: {val_mae:.4f}"
            print(msg)

    if val_loader is not None and best_state is not None:
        model.load_state_dict(best_state)
    return model

## STGCN Training

In [6]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from val_test import val_test
import pandas as pd
from print_results import print_results

n_folds = 30
models = {'STGCN': []}
name = list(models.keys())[0]
all_results_validation = {name: {'targets': [], 'preds': []}}
all_results_test = {name: {'targets': [], 'preds': [], 'subjects': []}}


for k in tqdm(range(n_folds)):
    
    model = STGCN().to(device)

    validation_pids, test_pids = val_test(participant_ids, k)
    print(f"Fold {k+1} | Validation Subs: {validation_pids} | Test Subs: {test_pids}")

    train_loader, val_loader, test_loader = cv_data_create(validation_pids, test_pids, save_dir, batch_size=bsize)
    trained_model = train_model(model, train_loader, experiment_seed=k, val_loader=val_loader, patience=150)

    val_t, val_p = evaluate_model(trained_model, val_loader, n_select_gaits=2)
    test_t, test_p = evaluate_model(trained_model, test_loader, n_select_gaits=2)

    all_results_validation[name]['targets'].extend(val_t)
    all_results_validation[name]['preds'].extend(val_p)
    all_results_test[name]['targets'].extend(test_t)
    all_results_test[name]['preds'].extend(test_p)
    all_results_test[name]['subjects'].extend(test_pids)

    mae_val = mean_absolute_error(val_t, val_p)
    rmse_val = np.sqrt(mean_squared_error(val_t, val_p))
    r2_val = r2_score(val_t, val_p)
    print(f"Fold {k + 1:02d} | {name} | Validation: MAE={mae_val:.3f}, RMSE={rmse_val:.3f}, R2={r2_val:.3f}\n")

test_results_df = print_results(all_results_validation, all_results_test, models)
test_results_df

  0%|          | 0/30 [00:00<?, ?it/s]

Fold 1 | Validation Subs: ['1', '2', '3', '4', '5'] | Test Subs: ['6', '7', '8', '10', '11']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.4332 | Val MAE: 3.2347
[Epoch 200/1000] Train MAE: 3.2611 | Val MAE: 4.4528
[Epoch 300/1000] Train MAE: 3.2098 | Val MAE: 3.1907
[Epoch 400/1000] Train MAE: 3.1276 | Val MAE: 3.7580
[Epoch 500/1000] Train MAE: 2.9026 | Val MAE: 9.1723
Early stopping at epoch 575 (no improvement for 150 epochs)
Fold 01 | STGCN | Validation: MAE=2.065, RMSE=4.034, R2=0.322

Fold 2 | Validation Subs: ['13', '14', '15', '17', '18'] | Test Subs: ['19', '20', '21', '22', '23']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.2824 | Val MAE: 9.6488
Early stopping at epoch 155 (no improvement for 150 epochs)
Fold 02 | STGCN | Validation: MAE=4.195, RMSE=5.079, R2=-1.150

Fold 3 | Validation Subs: ['24', '25', '26', '27', '28'] | Test Subs: ['29', '30', '31', '32', '33']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 2.9471 | Val MAE: 11.2957
Early stopping at epoch 154 (no improvement for 150 epochs)
Fold 03 | STGCN | Validation: MAE=4.806, RMSE=6.550, R2=-1.087

Fold 4 | Validation Subs: ['34', '35', '36', '37', '38'] | Test Subs: ['40', '41', '42', '43', '45']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.3207 | Val MAE: 10.4195
Early stopping at epoch 154 (no improvement for 150 epochs)
Fold 04 | STGCN | Validation: MAE=6.163, RMSE=7.882, R2=-0.249

Fold 5 | Validation Subs: ['46', '47', '48', '49', '51'] | Test Subs: ['52', '53', '54', '55', '56']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.4394 | Val MAE: 3.5424
[Epoch 200/1000] Train MAE: 3.3171 | Val MAE: 2.8992
[Epoch 300/1000] Train MAE: 3.3999 | Val MAE: 2.7155
[Epoch 400/1000] Train MAE: 2.9168 | Val MAE: 0.8901
[Epoch 500/1000] Train MAE: 2.7844 | Val MAE: 1.6421
Early stopping at epoch 588 (no improvement for 150 epochs)
Fold 05 | STGCN | Validation: MAE=0.538, RMSE=0.666, R2=0.985

Fold 6 | Validation Subs: ['57', '58', '59', '60', '61'] | Test Subs: ['62', '63', '64', '65', '66']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.5698 | Val MAE: 1.3093
[Epoch 200/1000] Train MAE: 3.3898 | Val MAE: 1.8256
[Epoch 300/1000] Train MAE: 3.1531 | Val MAE: 2.1172
[Epoch 400/1000] Train MAE: 2.9663 | Val MAE: 1.3799
[Epoch 500/1000] Train MAE: 2.7608 | Val MAE: 0.5232
Early stopping at epoch 594 (no improvement for 150 epochs)
Fold 06 | STGCN | Validation: MAE=0.317, RMSE=0.438, R2=0.000

Fold 7 | Validation Subs: ['67', '68', '69', '70', '71'] | Test Subs: ['72', '73', '74', '75', '76']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.4844 | Val MAE: 1.2207
[Epoch 200/1000] Train MAE: 3.3736 | Val MAE: 0.8586
Early stopping at epoch 289 (no improvement for 150 epochs)
Fold 07 | STGCN | Validation: MAE=0.294, RMSE=0.451, R2=0.000

Fold 8 | Validation Subs: ['77', '78', '79', '80', '81'] | Test Subs: ['82', '83', '84', '85', '86']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.4888 | Val MAE: 1.0458
Early stopping at epoch 188 (no improvement for 150 epochs)
Fold 08 | STGCN | Validation: MAE=0.420, RMSE=0.693, R2=0.000

Fold 9 | Validation Subs: ['87', '88', '89', '90', '92'] | Test Subs: ['94', '95', '97', '98', '99']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.5149 | Val MAE: 1.6000
[Epoch 200/1000] Train MAE: 3.2635 | Val MAE: 1.5609
Early stopping at epoch 253 (no improvement for 150 epochs)
Fold 09 | STGCN | Validation: MAE=0.803, RMSE=1.251, R2=0.000

Fold 10 | Validation Subs: ['100', '102', '103', '105', '106'] | Test Subs: ['107', '109', '111', '112', '113']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.4843 | Val MAE: 1.7615
[Epoch 200/1000] Train MAE: 3.3190 | Val MAE: 1.8033
Early stopping at epoch 247 (no improvement for 150 epochs)
Fold 10 | STGCN | Validation: MAE=0.809, RMSE=1.146, R2=0.000

Fold 11 | Validation Subs: ['115', '117', '118', '119', '120'] | Test Subs: ['121', '122', '123', '125', '126']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.4558 | Val MAE: 0.9493
[Epoch 200/1000] Train MAE: 3.3447 | Val MAE: 1.3427
Early stopping at epoch 270 (no improvement for 150 epochs)
Fold 11 | STGCN | Validation: MAE=0.508, RMSE=0.791, R2=0.000

Fold 12 | Validation Subs: ['127', '128', '129', '131', '133'] | Test Subs: ['134', '135', '136', '137', '138']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.5547 | Val MAE: 1.4770
[Epoch 200/1000] Train MAE: 3.4683 | Val MAE: 1.2901
Early stopping at epoch 227 (no improvement for 150 epochs)
Fold 12 | STGCN | Validation: MAE=0.693, RMSE=0.902, R2=0.000

Fold 13 | Validation Subs: ['139', '140', '141', '142', '143'] | Test Subs: ['144', '145', '148', '149', '150']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.4294 | Val MAE: 0.9704
[Epoch 200/1000] Train MAE: 2.9503 | Val MAE: 2.3341
[Epoch 300/1000] Train MAE: 2.7468 | Val MAE: 1.6171
[Epoch 400/1000] Train MAE: 2.6665 | Val MAE: 0.9409
Early stopping at epoch 408 (no improvement for 150 epochs)
Fold 13 | STGCN | Validation: MAE=0.492, RMSE=0.765, R2=0.000

Fold 14 | Validation Subs: ['151', '153', '154', '155', '156'] | Test Subs: ['157', '158', '159', '160', '162']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.6342 | Val MAE: 2.4363
[Epoch 200/1000] Train MAE: 3.5438 | Val MAE: 2.4658
[Epoch 300/1000] Train MAE: 3.3070 | Val MAE: 2.7967
Early stopping at epoch 378 (no improvement for 150 epochs)
Fold 14 | STGCN | Validation: MAE=1.029, RMSE=1.344, R2=0.000

Fold 15 | Validation Subs: ['164', '165', '167', '168', '171'] | Test Subs: ['173', '174', '175', '179', '180', '183', '184', '185', '187', '188']
Created 700 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.6423 | Val MAE: 0.6210
[Epoch 200/1000] Train MAE: 3.3431 | Val MAE: 0.8013
Early stopping at epoch 278 (no improvement for 150 epochs)
Fold 15 | STGCN | Validation: MAE=0.159, RMSE=0.214, R2=0.000

Fold 16 | Validation Subs: ['6', '7', '8', '10', '11'] | Test Subs: ['1', '2', '3', '4', '5']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.2332 | Val MAE: 2.8389
[Epoch 200/1000] Train MAE: 3.1080 | Val MAE: 3.7739
Early stopping at epoch 217 (no improvement for 150 epochs)
Fold 16 | STGCN | Validation: MAE=1.769, RMSE=2.665, R2=0.662

Fold 17 | Validation Subs: ['19', '20', '21', '22', '23'] | Test Subs: ['13', '14', '15', '17', '18']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.1208 | Val MAE: 5.7484
Early stopping at epoch 155 (no improvement for 150 epochs)
Fold 17 | STGCN | Validation: MAE=3.297, RMSE=3.532, R2=-0.091

Fold 18 | Validation Subs: ['29', '30', '31', '32', '33'] | Test Subs: ['24', '25', '26', '27', '28']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 2.9243 | Val MAE: 10.6758
Early stopping at epoch 154 (no improvement for 150 epochs)
Fold 18 | STGCN | Validation: MAE=5.539, RMSE=6.650, R2=-0.209

Fold 19 | Validation Subs: ['40', '41', '42', '43', '45'] | Test Subs: ['34', '35', '36', '37', '38']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.1442 | Val MAE: 5.6135
[Epoch 200/1000] Train MAE: 2.9359 | Val MAE: 6.1726
[Epoch 300/1000] Train MAE: 2.8898 | Val MAE: 5.5927
[Epoch 400/1000] Train MAE: 2.6884 | Val MAE: 6.8066
Early stopping at epoch 492 (no improvement for 150 epochs)
Fold 19 | STGCN | Validation: MAE=4.459, RMSE=7.800, R2=-0.097

Fold 20 | Validation Subs: ['52', '53', '54', '55', '56'] | Test Subs: ['46', '47', '48', '49', '51']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.3125 | Val MAE: 0.6950
[Epoch 200/1000] Train MAE: 3.3136 | Val MAE: 1.1855
[Epoch 300/1000] Train MAE: 3.1391 | Val MAE: 0.3018
[Epoch 400/1000] Train MAE: 2.7546 | Val MAE: 0.8437
Early stopping at epoch 415 (no improvement for 150 epochs)
Fold 20 | STGCN | Validation: MAE=0.228, RMSE=0.290, R2=0.000

Fold 21 | Validation Subs: ['62', '63', '64', '65', '66'] | Test Subs: ['57', '58', '59', '60', '61']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.4149 | Val MAE: 1.6573
[Epoch 200/1000] Train MAE: 3.1260 | Val MAE: 1.9986
Early stopping at epoch 209 (no improvement for 150 epochs)
Fold 21 | STGCN | Validation: MAE=0.313, RMSE=0.427, R2=0.000

Fold 22 | Validation Subs: ['72', '73', '74', '75', '76'] | Test Subs: ['67', '68', '69', '70', '71']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.3337 | Val MAE: 0.4225
[Epoch 200/1000] Train MAE: 3.3207 | Val MAE: 0.3272
[Epoch 300/1000] Train MAE: 3.1961 | Val MAE: 0.6754
Early stopping at epoch 339 (no improvement for 150 epochs)
Fold 22 | STGCN | Validation: MAE=0.110, RMSE=0.162, R2=0.000

Fold 23 | Validation Subs: ['82', '83', '84', '85', '86'] | Test Subs: ['77', '78', '79', '80', '81']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.4485 | Val MAE: 1.2567
[Epoch 200/1000] Train MAE: 3.2399 | Val MAE: 1.1349
[Epoch 300/1000] Train MAE: 3.0064 | Val MAE: 1.2870
[Epoch 400/1000] Train MAE: 2.8753 | Val MAE: 1.2746
Early stopping at epoch 452 (no improvement for 150 epochs)
Fold 23 | STGCN | Validation: MAE=0.526, RMSE=0.712, R2=0.000

Fold 24 | Validation Subs: ['94', '95', '97', '98', '99'] | Test Subs: ['87', '88', '89', '90', '92']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.6480 | Val MAE: 0.9606
[Epoch 200/1000] Train MAE: 3.2544 | Val MAE: 0.8681
Early stopping at epoch 275 (no improvement for 150 epochs)
Fold 24 | STGCN | Validation: MAE=0.482, RMSE=0.826, R2=0.000

Fold 25 | Validation Subs: ['107', '109', '111', '112', '113'] | Test Subs: ['100', '102', '103', '105', '106']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.4796 | Val MAE: 1.0281
[Epoch 200/1000] Train MAE: 3.3009 | Val MAE: 0.9763
Early stopping at epoch 236 (no improvement for 150 epochs)
Fold 25 | STGCN | Validation: MAE=0.233, RMSE=0.293, R2=0.000

Fold 26 | Validation Subs: ['121', '122', '123', '125', '126'] | Test Subs: ['115', '117', '118', '119', '120']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.5461 | Val MAE: 0.9683
Early stopping at epoch 184 (no improvement for 150 epochs)
Fold 26 | STGCN | Validation: MAE=0.266, RMSE=0.310, R2=0.000

Fold 27 | Validation Subs: ['134', '135', '136', '137', '138'] | Test Subs: ['127', '128', '129', '131', '133']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.3744 | Val MAE: 1.0782
[Epoch 200/1000] Train MAE: 3.3142 | Val MAE: 0.5801
Early stopping at epoch 299 (no improvement for 150 epochs)
Fold 27 | STGCN | Validation: MAE=0.359, RMSE=0.416, R2=0.000

Fold 28 | Validation Subs: ['144', '145', '148', '149', '150'] | Test Subs: ['139', '140', '141', '142', '143']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.5306 | Val MAE: 1.5462
[Epoch 200/1000] Train MAE: 3.2376 | Val MAE: 0.8985
[Epoch 300/1000] Train MAE: 3.1010 | Val MAE: 1.0416
Early stopping at epoch 391 (no improvement for 150 epochs)
Fold 28 | STGCN | Validation: MAE=0.261, RMSE=0.370, R2=0.000

Fold 29 | Validation Subs: ['157', '158', '159', '160', '162'] | Test Subs: ['151', '153', '154', '155', '156']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.2547 | Val MAE: 2.0355
Early stopping at epoch 181 (no improvement for 150 epochs)
Fold 29 | STGCN | Validation: MAE=1.512, RMSE=1.665, R2=0.000

Fold 30 | Validation Subs: ['173', '174', '175', '179', '180', '183', '184', '185', '187', '188'] | Test Subs: ['164', '165', '167', '168', '171']
Created 700 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 3.5926 | Val MAE: 1.2791
[Epoch 200/1000] Train MAE: 3.3995 | Val MAE: 0.8622
Early stopping at epoch 210 (no improvement for 150 epochs)
Fold 30 | STGCN | Validation: MAE=0.460, RMSE=0.625, R2=0.000


=== Validation Performance (across all folds) ===
            MAE      RMSE        R2  Pearson r     Pearson p
STGCN  1.405245  3.033961  0.698585   0.835883  1.069059e-41

=== Test Performance (across all folds) ===

           MAE      RMSE        R2  Pearson r     Pearson p
STGCN  2.17633  3.883727  0.506096   0.723166  2.269686e-26

In [7]:
from ci import *

ci_results = {}

name = "STGCN"

ci_results[name] = subject_bootstrap_ci(
    all_results_test[name]['targets'],
    all_results_test[name]['preds'],
    all_results_test[name]['subjects'])

pd.DataFrame(ci_results['STGCN'])

               MAE            RMSE             R2       Pearson r
mean       2.17633        3.883727       0.506096        0.723166
ci    [1.8, 2.565]  [3.084, 4.499]  [0.337, 0.66]  [0.635, 0.817]

## Loading Lesion Left Classification Data

In [4]:
save_dir = 'data_clf'
loaded_dir = 'csv_clf'
# preprocess_and_save_data(loaded_dir, save_dir)
all_files = filter_valid_files(os.listdir(loaded_dir))
participant_ids = sorted({re.search(r'ID(\d+)_', f).group(1) for f in all_files}, key=lambda x: int(x))

## Classification Evaluation Function

In [5]:
def evaluate_model_clf(model, test_loader, n_select_gaits, num_classes=3):
    """Classification evaluation: aggregate unit-level predictions per participant (majority vote)."""
    model.eval()
    device = next(model.parameters()).device

    t = []
    p = []

    with torch.no_grad():
        for batch in test_loader:
            if len(batch) == 3:
                x_load_list, y_batch, _ = batch
            else:
                x_load_list, y_batch = batch

            for i, x_load_sample in enumerate(x_load_list):
                x_task = x_load_sample[:6]
                num_units = len(x_task) - n_select_gaits + 1

                unit_preds = []

                for start_idx in range(num_units):
                    unit = x_task[start_idx:start_idx + n_select_gaits]
                    unit_tensor = unit.unsqueeze(0).to(device)

                    logits = model(unit_tensor)
                    pred_class = logits.argmax(dim=1).item()
                    unit_preds.append(pred_class)

                participant_target = y_batch[i].item()
                participant_pred = int(np.bincount(unit_preds).argmax())

                t.append(participant_target)
                p.append(participant_pred)

    return t, p

## Classification Model Training Function

In [6]:
def train_model_clf(model, train_loader, experiment_seed=42, num_epochs=1000, N_gaits=2, val_loader=None, patience=50, num_classes=3):
    set_deterministic(experiment_seed)
    random.seed(experiment_seed)
    np.random.seed(experiment_seed)

    all_x = []
    all_y = []

    for batch in train_loader:
        if len(batch) == 3:
            x_load_list, y_batch, _ = batch
        else:
            x_load_list, y_batch = batch
        all_x.extend(x_load_list)
        all_y.extend(y_batch)

    optimized_train_loader = create_gait_units_dataloader(all_x, all_y, N_gaits=N_gaits,
                                                          batch_size=bsize, shuffle=True)

    val_unit_loader = None
    if val_loader is not None:
        val_x, val_y = [], []
        for batch in val_loader:
            if len(batch) == 3:
                x_load_list, y_batch, _ = batch
            else:
                x_load_list, y_batch = batch
            val_x.extend(x_load_list)
            val_y.extend(y_batch)
        val_unit_loader = create_gait_units_dataloader(val_x, val_y, N_gaits=N_gaits,
                                                       batch_size=bsize, shuffle=False)

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs)

    best_val_loss = float('inf')
    best_state = None
    epochs_no_improve = 0

    print("Starting training...")
    for epoch in range(num_epochs):
        model.train()
        total_loss = 0

        for x_batch, y_batch in optimized_train_loader:
            x_batch = x_batch.to(device)
            y_batch = y_batch.to(device).long()

            logits = model(x_batch)
            loss = F.cross_entropy(logits, y_batch)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        scheduler.step()

        if val_unit_loader is not None:
            model.eval()
            val_loss_sum, val_n = 0.0, 0
            with torch.no_grad():
                for x_batch, y_batch in val_unit_loader:
                    x_batch = x_batch.to(device)
                    y_batch = y_batch.to(device).long()
                    logits = model(x_batch)
                    val_loss_sum += F.cross_entropy(logits, y_batch, reduction='sum').item()
                    val_n += x_batch.size(0)
            val_loss = val_loss_sum / val_n
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                epochs_no_improve = 0
            else:
                epochs_no_improve += 1
            if epochs_no_improve >= patience:
                print(f"Early stopping at epoch {epoch + 1} (no improvement for {patience} epochs)")
                if best_state is not None:
                    model.load_state_dict(best_state)
                break

        if (epoch + 1) % 100 == 0:
            avg_loss = total_loss / len(optimized_train_loader)
            msg = f"[Epoch {epoch + 1}/{num_epochs}] Train CE loss: {avg_loss:.4f}"
            if val_unit_loader is not None:
                val_t, val_p = evaluate_model_clf(model, val_loader, n_select_gaits=N_gaits, num_classes=num_classes)
                val_acc = np.mean(np.array(val_t) == np.array(val_p))
                msg += f" | Val CE loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}"
            print(msg)

    if val_loader is not None and best_state is not None:
        model.load_state_dict(best_state)
    return model

## STGCN Training Classification

In [7]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from val_test import val_test

n_folds = 30
models_clf = {'STGCN': []}
name = list(models_clf.keys())[0]

all_results_validation_clf = {name: {'targets': [], 'preds': []}}
all_results_test_clf = {name: {'targets': [], 'preds': [], 'subjects': []}}

for k in tqdm(range(n_folds)):

    model = STGCN(output_dim=3).to(device)

    validation_pids, test_pids = val_test(participant_ids, k)
    print(f"Fold {k+1} | Validation Subs: {validation_pids} | Test Subs: {test_pids}")

    train_loader, val_loader, test_loader = cv_data_create(validation_pids, test_pids, save_dir, batch_size=bsize)
    trained_model = train_model_clf(model, train_loader, experiment_seed=k, num_epochs=1000, N_gaits=2,
                                    val_loader=val_loader, patience=150, num_classes=3)

    val_t, val_p = evaluate_model_clf(trained_model, val_loader, n_select_gaits=2, num_classes=3)
    test_t, test_p = evaluate_model_clf(trained_model, test_loader, n_select_gaits=2, num_classes=3)

    all_results_validation_clf[name]['targets'].extend(val_t)
    all_results_validation_clf[name]['preds'].extend(val_p)

    all_results_test_clf[name]['targets'].extend(test_t)
    all_results_test_clf[name]['preds'].extend(test_p)
    all_results_test_clf[name]['subjects'].extend(test_pids)

    acc_val = accuracy_score(val_t, val_p)
    f1m_val = f1_score(val_t, val_p, average='macro')
    print(f"Fold {k + 1:02d} | {name} | Validation: Acc={acc_val:.3f}, F1-macro={f1m_val:.3f}\n")

# Overall pooled (OOF) metrics across all folds
val_t_all = np.array(all_results_validation_clf[name]['targets'])
val_p_all = np.array(all_results_validation_clf[name]['preds'])
test_t_all = np.array(all_results_test_clf[name]['targets'])
test_p_all = np.array(all_results_test_clf[name]['preds'])

def classification_metrics(t, p):
    return {
        'Accuracy': accuracy_score(t, p),
        'F1 (weighted)': f1_score(t, p, average='weighted'),
        'F1 (macro)': f1_score(t, p, average='macro'),
        'Precision (weighted)': precision_score(t, p, average='weighted', zero_division=0),
        'Precision (macro)': precision_score(t, p, average='macro', zero_division=0),
        'Recall (weighted)': recall_score(t, p, average='weighted', zero_division=0),
        'Recall (macro)': recall_score(t, p, average='macro', zero_division=0),
    }

results_val = classification_metrics(val_t_all, val_p_all)
results_test = classification_metrics(test_t_all, test_p_all)

print("\n=== Validation Performance (across all folds) ===")
print(pd.DataFrame({name: results_val}).T)

print("\n=== Test Performance (across all folds) ===")
results_test_df = pd.DataFrame({name: results_test}).T
results_test_df

  0%|          | 0/30 [00:00<?, ?it/s]

Fold 1 | Validation Subs: ['1', '2', '3', '4', '5'] | Test Subs: ['6', '7', '8', '10', '11']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2081 | Val CE loss: 2.9577 | Val Acc: 0.4000
Early stopping at epoch 151 (no improvement for 150 epochs)
Fold 01 | STGCN | Validation: Acc=0.000, F1-macro=0.000

Fold 2 | Validation Subs: ['13', '14', '15', '17', '18'] | Test Subs: ['19', '20', '21', '22', '23']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.1939 | Val CE loss: 1.9953 | Val Acc: 0.6000
Early stopping at epoch 151 (no improvement for 150 epochs)
Fold 02 | STGCN | Validation: Acc=0.000, F1-macro=0.000

Fold 3 | Validation Subs: ['24', '25', '26', '27', '28'] | Test Subs: ['29', '30', '31', '32', '33']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2286 | Val CE loss: 3.6179 | Val Acc: 0.4000
Early stopping at epoch 151 (no improvement for 150 epochs)
Fold 03 | STGCN | Validation: Acc=0.000, F1-macro=0.000

Fold 4 | Validation Subs: ['34', '35', '36', '37', '38'] | Test Subs: ['40', '41', '42', '43', '45']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.1855 | Val CE loss: 2.9767 | Val Acc: 0.4000
Early stopping at epoch 151 (no improvement for 150 epochs)
Fold 04 | STGCN | Validation: Acc=0.000, F1-macro=0.000

Fold 5 | Validation Subs: ['46', '47', '48', '49', '51'] | Test Subs: ['52', '53', '54', '55', '56']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2957 | Val CE loss: 1.6183 | Val Acc: 0.6000
[Epoch 200/1000] Train CE loss: 0.1482 | Val CE loss: 0.9272 | Val Acc: 0.8000
[Epoch 300/1000] Train CE loss: 0.0859 | Val CE loss: 0.9167 | Val Acc: 0.8000
Early stopping at epoch 373 (no improvement for 150 epochs)
Fold 05 | STGCN | Validation: Acc=0.800, F1-macro=0.619

Fold 6 | Validation Subs: ['57', '58', '59', '60', '61'] | Test Subs: ['62', '63', '64', '65', '66']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2458 | Val CE loss: 0.0353 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1175 | Val CE loss: 0.0045 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.1388 | Val CE loss: 0.0069 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0506 | Val CE loss: 0.0018 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0232 | Val CE loss: 0.0029 | Val Acc: 1.0000
Early stopping at epoch 579 (no improvement for 150 epochs)
Fold 06 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 7 | Validation Subs: ['67', '68', '69', '70', '71'] | Test Subs: ['72', '73', '74', '75', '76']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.3195 | Val CE loss: 0.1671 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1278 | Val CE loss: 0.0944 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0938 | Val CE loss: 0.0260 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0422 | Val CE loss: 0.0112 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0348 | Val CE loss: 0.0140 | Val Acc: 1.0000
[Epoch 600/1000] Train CE loss: 0.0220 | Val CE loss: 0.0273 | Val Acc: 1.0000
Early stopping at epoch 663 (no improvement for 150 epochs)
Fold 07 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 8 | Validation Subs: ['77', '78', '79', '80', '81'] | Test Subs: ['82', '83', '84', '85', '86']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.3012 | Val CE loss: 0.1520 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1634 | Val CE loss: 0.1447 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0717 | Val CE loss: 0.1796 | Val Acc: 1.0000
Early stopping at epoch 318 (no improvement for 150 epochs)
Fold 08 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 9 | Validation Subs: ['87', '88', '89', '90', '92'] | Test Subs: ['94', '95', '97', '98', '99']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2385 | Val CE loss: 0.1074 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1143 | Val CE loss: 0.0560 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0525 | Val CE loss: 0.0447 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0968 | Val CE loss: 0.1182 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0237 | Val CE loss: 0.0157 | Val Acc: 1.0000
[Epoch 600/1000] Train CE loss: 0.0103 | Val CE loss: 0.0414 | Val Acc: 1.0000
Early stopping at epoch 634 (no improvement for 150 epochs)
Fold 09 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 10 | Validation Subs: ['100', '102', '103', '105', '106'] | Test Subs: ['107', '109', '111', '112', '113']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.3105 | Val CE loss: 0.1562 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1556 | Val CE loss: 0.0714 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0986 | Val CE loss: 0.0562 | Val Acc: 1.0000
Early stopping at epoch 395 (no improvement for 150 epochs)
Fold 10 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 11 | Validation Subs: ['115', '117', '118', '119', '120'] | Test Subs: ['121', '122', '123', '125', '126']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2864 | Val CE loss: 0.1129 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1493 | Val CE loss: 0.0580 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.1298 | Val CE loss: 0.0307 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.1416 | Val CE loss: 0.0106 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0289 | Val CE loss: 0.0060 | Val Acc: 1.0000
[Epoch 600/1000] Train CE loss: 0.0513 | Val CE loss: 0.0002 | Val Acc: 1.0000
[Epoch 700/1000] Train CE loss: 0.0067 | Val CE loss: 0.0031 | Val Acc: 1.0000
Early stopping at epoch 750 (no improvement for 150 epochs)
Fold 11 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 12 | Validation Subs: ['127', '128', '129', '131', '133'] | Test Subs: ['134', '135', '136', '137', '138']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2281 | Val CE loss: 0.1904 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1122 | Val CE loss: 0.0837 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0532 | Val CE loss: 0.1260 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0305 | Val CE loss: 0.0445 | Val Acc: 1.0000
Early stopping at epoch 483 (no improvement for 150 epochs)
Fold 12 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 13 | Validation Subs: ['139', '140', '141', '142', '143'] | Test Subs: ['144', '145', '148', '149', '150']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.3055 | Val CE loss: 0.0607 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1093 | Val CE loss: 0.0335 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0558 | Val CE loss: 0.0057 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0292 | Val CE loss: 0.0576 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0240 | Val CE loss: 0.0019 | Val Acc: 1.0000
[Epoch 600/1000] Train CE loss: 0.0265 | Val CE loss: 0.0202 | Val Acc: 1.0000
Early stopping at epoch 621 (no improvement for 150 epochs)
Fold 13 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 14 | Validation Subs: ['151', '153', '154', '155', '156'] | Test Subs: ['157', '158', '159', '160', '162']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.3320 | Val CE loss: 0.3245 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1362 | Val CE loss: 0.4418 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0814 | Val CE loss: 0.4340 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0670 | Val CE loss: 0.4068 | Val Acc: 1.0000
Early stopping at epoch 492 (no improvement for 150 epochs)
Fold 14 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 15 | Validation Subs: ['164', '165', '167', '168', '171'] | Test Subs: ['173', '174', '175', '179', '180', '183', '184', '185', '187', '188']
Created 700 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2771 | Val CE loss: 0.0336 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0795 | Val CE loss: 0.0035 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0529 | Val CE loss: 0.0004 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0271 | Val CE loss: 0.0589 | Val Acc: 1.0000
Early stopping at epoch 495 (no improvement for 150 epochs)
Fold 15 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 16 | Validation Subs: ['6', '7', '8', '10', '11'] | Test Subs: ['1', '2', '3', '4', '5']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2601 | Val CE loss: 0.8700 | Val Acc: 0.6000
[Epoch 200/1000] Train CE loss: 0.1133 | Val CE loss: 1.4715 | Val Acc: 0.8000
Early stopping at epoch 242 (no improvement for 150 epochs)
Fold 16 | STGCN | Validation: Acc=0.400, F1-macro=0.190

Fold 17 | Validation Subs: ['19', '20', '21', '22', '23'] | Test Subs: ['13', '14', '15', '17', '18']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2470 | Val CE loss: 3.3363 | Val Acc: 0.0000
Early stopping at epoch 151 (no improvement for 150 epochs)
Fold 17 | STGCN | Validation: Acc=0.000, F1-macro=0.000

Fold 18 | Validation Subs: ['29', '30', '31', '32', '33'] | Test Subs: ['24', '25', '26', '27', '28']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2507 | Val CE loss: 2.3017 | Val Acc: 0.6000
Early stopping at epoch 157 (no improvement for 150 epochs)
Fold 18 | STGCN | Validation: Acc=0.400, F1-macro=0.286

Fold 19 | Validation Subs: ['40', '41', '42', '43', '45'] | Test Subs: ['34', '35', '36', '37', '38']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2405 | Val CE loss: 1.0141 | Val Acc: 0.6000
[Epoch 200/1000] Train CE loss: 0.1245 | Val CE loss: 0.9742 | Val Acc: 0.4000
[Epoch 300/1000] Train CE loss: 0.0633 | Val CE loss: 0.8709 | Val Acc: 0.8000
Early stopping at epoch 394 (no improvement for 150 epochs)
Fold 19 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 20 | Validation Subs: ['52', '53', '54', '55', '56'] | Test Subs: ['46', '47', '48', '49', '51']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2897 | Val CE loss: 0.0337 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1575 | Val CE loss: 0.0028 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0500 | Val CE loss: 0.0026 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0497 | Val CE loss: 0.0032 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0408 | Val CE loss: 0.0032 | Val Acc: 1.0000
[Epoch 600/1000] Train CE loss: 0.0124 | Val CE loss: 0.0008 | Val Acc: 1.0000
Early stopping at epoch 615 (no improvement for 150 epochs)
Fold 20 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 21 | Validation Subs: ['62', '63', '64', '65', '66'] | Test Subs: ['57', '58', '59', '60', '61']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2512 | Val CE loss: 0.1335 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1796 | Val CE loss: 0.1828 | Val Acc: 1.0000
Early stopping at epoch 216 (no improvement for 150 epochs)
Fold 21 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 22 | Validation Subs: ['72', '73', '74', '75', '76'] | Test Subs: ['67', '68', '69', '70', '71']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2602 | Val CE loss: 0.0192 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1172 | Val CE loss: 0.0796 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.1051 | Val CE loss: 0.0022 | Val Acc: 1.0000
Early stopping at epoch 319 (no improvement for 150 epochs)
Fold 22 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 23 | Validation Subs: ['82', '83', '84', '85', '86'] | Test Subs: ['77', '78', '79', '80', '81']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2516 | Val CE loss: 0.1151 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1393 | Val CE loss: 0.1428 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0740 | Val CE loss: 0.0247 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0484 | Val CE loss: 0.0081 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0283 | Val CE loss: 0.0044 | Val Acc: 1.0000
[Epoch 600/1000] Train CE loss: 0.0250 | Val CE loss: 0.0006 | Val Acc: 1.0000
[Epoch 700/1000] Train CE loss: 0.0083 | Val CE loss: 0.0022 | Val Acc: 1.0000
Early stopping at epoch 786 (no improvement for 150 epochs)
Fold 23 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 24 | Validation Subs: ['94', '95', '97', '98', '99'] | Test Subs: ['87', '88', '89', '90', '92']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2469 | Val CE loss: 0.0857 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1264 | Val CE loss: 0.0434 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0573 | Val CE loss: 0.0097 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0405 | Val CE loss: 0.0048 | Val Acc: 1.0000
Early stopping at epoch 439 (no improvement for 150 epochs)
Fold 24 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 25 | Validation Subs: ['107', '109', '111', '112', '113'] | Test Subs: ['100', '102', '103', '105', '106']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.3461 | Val CE loss: 0.3781 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1872 | Val CE loss: 0.0845 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0833 | Val CE loss: 0.0469 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0490 | Val CE loss: 0.0428 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0404 | Val CE loss: 0.0352 | Val Acc: 1.0000
[Epoch 600/1000] Train CE loss: 0.0401 | Val CE loss: 0.0228 | Val Acc: 1.0000
Early stopping at epoch 604 (no improvement for 150 epochs)
Fold 25 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 26 | Validation Subs: ['121', '122', '123', '125', '126'] | Test Subs: ['115', '117', '118', '119', '120']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2817 | Val CE loss: 0.0863 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1532 | Val CE loss: 0.0348 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0571 | Val CE loss: 0.0059 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0475 | Val CE loss: 0.0013 | Val Acc: 1.0000
Early stopping at epoch 433 (no improvement for 150 epochs)
Fold 26 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 27 | Validation Subs: ['134', '135', '136', '137', '138'] | Test Subs: ['127', '128', '129', '131', '133']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2555 | Val CE loss: 0.2188 | Val Acc: 0.8000
[Epoch 200/1000] Train CE loss: 0.1495 | Val CE loss: 0.0423 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0915 | Val CE loss: 0.3327 | Val Acc: 0.8000
[Epoch 400/1000] Train CE loss: 0.0467 | Val CE loss: 0.1041 | Val Acc: 1.0000
Early stopping at epoch 480 (no improvement for 150 epochs)
Fold 27 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 28 | Validation Subs: ['144', '145', '148', '149', '150'] | Test Subs: ['139', '140', '141', '142', '143']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2898 | Val CE loss: 0.0105 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1697 | Val CE loss: 0.0003 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0628 | Val CE loss: 0.0019 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0428 | Val CE loss: 0.0010 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0341 | Val CE loss: 0.0001 | Val Acc: 1.0000
[Epoch 600/1000] Train CE loss: 0.0329 | Val CE loss: 0.0001 | Val Acc: 1.0000
Early stopping at epoch 625 (no improvement for 150 epochs)
Fold 28 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 29 | Validation Subs: ['157', '158', '159', '160', '162'] | Test Subs: ['151', '153', '154', '155', '156']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2079 | Val CE loss: 0.0963 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1156 | Val CE loss: 0.0153 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.1702 | Val CE loss: 0.0031 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0241 | Val CE loss: 0.0045 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0160 | Val CE loss: 0.0032 | Val Acc: 1.0000
[Epoch 600/1000] Train CE loss: 0.0160 | Val CE loss: 0.0102 | Val Acc: 1.0000
[Epoch 700/1000] Train CE loss: 0.0098 | Val CE loss: 0.0027 | Val Acc: 1.0000
Early stopping at epoch 738 (no improvement for 150 epochs)
Fold 29 | STGCN | Validation: Acc=1.000, F1-macro=1.000

Fold 30 | Validation Subs: ['173', '174', '175', '179', '180', '183', '184', '185', '187', '188'] | Test Subs: ['164', '165', '167', '168', '171']
Created 700 gait windows
Created 50 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.2705 | Val CE loss: 0.0878 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.1193 | Val CE loss: 0.0258 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0530 | Val CE loss: 0.0552 | Val Acc: 1.0000
Early stopping at epoch 377 (no improvement for 150 epochs)
Fold 30 | STGCN | Validation: Acc=1.000, F1-macro=1.000


=== Validation Performance (across all folds) ===
       Accuracy  F1 (weighted)  F1 (macro)  Precision (weighted)  \
STGCN  0.793548       0.745398     0.50864              0.775315

       Precision (macro)  Recall (weighted)  Recall (macro)
STGCN           0.680952           0.793548        0.479365

=== Test Performance (across all folds) ===

,Accuracy,F1 (weighted),F1 (macro),Precision (weighted),Precision (macro),Recall (weighted),Recall (macro)
STGCN,0.754839,0.680571,0.391627,0.677241,0.477395,0.754839,0.4

In [9]:
from ci_class import subject_bootstrap_ci_class

ci_results = {}

name = "STGCN"

ci_results[name] = subject_bootstrap_ci_class(
    all_results_test_clf[name]['targets'],
    all_results_test_clf[name]['preds'],
    all_results_test_clf[name]['subjects'])

pd.DataFrame(ci_results['STGCN'])

,Accuracy,F1 (weighted),F1 (macro),Precision (weighted),Precision (macro),Recall (weighted),Recall (macro)
mean,0.754839,0.680571,0.391627,0.677241,0.477395,0.754839,0.4
ci,"[0.701, 0.806]","[0.608, 0.748]","[0.331, 0.442]","[0.592, 0.769]","[0.38, 0.589]","[0.701, 0.806]","[0.357, 0.438]"