In [1]:
import os
import re
import random
import numpy as np
import pandas as pd
import torch
import time
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from tqdm.notebook import tqdm

from data_utils_load import *
from tcn import TCN

device = torch.device('cuda:1' if torch.cuda.is_available() else 'cpu')

def filter_valid_files(file_list):
    valid_files = []
    for file in file_list:
        file = file.strip()
        if re.match(r'^ID\d+_\d+\.csv$', file):
            valid_files.append(file)
    return valid_files

def set_deterministic(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

bsize = 64

## Loading POMA Data

In [2]:
save_dir = 'data'
loaded_dir = 'csv_r'
# preprocess_and_save_data(loaded_dir, save_dir)
all_files = filter_valid_files(os.listdir(loaded_dir))
participant_ids = sorted({re.search(r'ID(\d+)_', f).group(1) for f in all_files}, key=lambda x: int(x))

## Gait Unit Creation

In [2]:
class GaitUnitsDataset(Dataset):
    def __init__(self, x_load_list, y_batch, N_gaits):
        self.unit_samples = []
        self.unit_labels = []
        
        for x_task, y_task in zip(x_load_list, y_batch):
            L = x_task.size(0)
            num_units = L - N_gaits + 1
            units = [x_task[start:start + N_gaits] for start in range(num_units)]
            self.unit_samples.extend(units)
            self.unit_labels.extend([y_task] * num_units)
        print(f"Created {len(self.unit_samples)} gait windows")
    
    def __len__(self):
        return len(self.unit_samples)
    
    def __getitem__(self, idx):
        return self.unit_samples[idx], self.unit_labels[idx]


def create_gait_units_dataloader(x_load_list, y_batch, N_gaits, batch_size=64, shuffle=True):
    dataset = GaitUnitsDataset(x_load_list, y_batch, N_gaits)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

## Regression Evaluation Function

In [3]:
def evaluate_model(model, test_loader, n_select_gaits):

    model.eval()
    device = next(model.parameters()).device

    t = []
    p = []

    with torch.no_grad():
        for batch in test_loader:
            if len(batch) == 3:
                x_load_list, y_batch, _ = batch
            else:
                x_load_list, y_batch = batch

            for i, x_load_sample in enumerate(x_load_list):
                x_task = x_load_sample[:6]
                num_units = len(x_task) - n_select_gaits + 1

                unit_preds = []
                    
                for start_idx in range(num_units):
                    unit = x_task[start_idx:start_idx + n_select_gaits]
                    unit_tensor = unit.unsqueeze(0).to(device)
                    y_target = y_batch[i:i+1].to(device)
                        
                    y_pred = model(unit_tensor)
                    unit_preds.append(y_pred.item())

                participant_target = y_target.item()
                participant_pred = float(np.median(np.array(unit_preds)))

                t.append(participant_target)
                p.append(participant_pred)
    
    return t, p

## Regression Model Training Function

In [4]:
def train_model(model, train_loader, experiment_seed=42, num_epochs=1000, N_gaits=2, val_loader=None, patience=50):
    set_deterministic(experiment_seed)
    random.seed(experiment_seed)
    np.random.seed(experiment_seed)

    all_x = []
    all_y = []
    
    for batch in train_loader:
        if len(batch) == 3:
            x_load_list, y_batch, _ = batch
        else:
            x_load_list, y_batch = batch
        all_x.extend(x_load_list)
        all_y.extend(y_batch)
    
    optimized_train_loader = create_gait_units_dataloader(all_x, all_y, N_gaits=N_gaits, 
                                                          batch_size=bsize, shuffle=True)
    
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs)

    best_val_mae = float('inf')
    best_state = None
    epochs_no_improve = 0

    print("Starting training...")
    for epoch in range(num_epochs):
        model.train()
        total_loss = 0
        
        for x_batch, y_batch in optimized_train_loader:
            x_batch = x_batch.to(device) 
            y_batch = y_batch.to(device)  
            
            y_pred = model(x_batch).view(-1)
            loss = F.l1_loss(y_pred, y_batch)
            
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        
        scheduler.step()

        if val_loader is not None:
            val_t, val_p = evaluate_model(model, val_loader, n_select_gaits=N_gaits)
            val_mae = np.mean(np.abs(np.array(val_t) - np.array(val_p)))
            if val_mae < best_val_mae:
                best_val_mae = val_mae
                best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                epochs_no_improve = 0
            else:
                epochs_no_improve += 1
            if epochs_no_improve >= patience:
                print(f"Early stopping at epoch {epoch + 1} (no improvement for {patience} epochs)")
                if best_state is not None:
                    model.load_state_dict(best_state)
                break
        
        if (epoch + 1) % 100 == 0:
            avg_loss = total_loss / len(optimized_train_loader)
            msg = f"[Epoch {epoch + 1}/{num_epochs}] Train MAE: {avg_loss:.4f}"
            if val_loader is not None:
                msg += f" | Val MAE: {val_mae:.4f}"
            print(msg)

    if val_loader is not None and best_state is not None:
        model.load_state_dict(best_state)
    return model

## TCN Regressor Training

In [6]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from val_test import val_test
from print_results import print_results

n_folds = 30
models = {'TCN': []}
name = list(models.keys())[0]
all_results_validation = {name: {'targets': [], 'preds': []}}
all_results_test = {name: {'targets': [], 'preds': [], 'subjects': []}}


for k in tqdm(range(n_folds)):
    
    model = TCN(N_gaits=2).to(device)

    validation_pids, test_pids = val_test(participant_ids, k)
    print(f"Fold {k+1} | Validation Subs: {validation_pids} | Test Subs: {test_pids}")

    train_loader, val_loader, test_loader = cv_data_create(validation_pids, test_pids, save_dir, batch_size=bsize)
    trained_model = train_model(model, train_loader, experiment_seed=k, val_loader=val_loader, patience=200)

    val_t, val_p = evaluate_model(trained_model, val_loader, n_select_gaits=2)
    test_t, test_p = evaluate_model(trained_model, test_loader, n_select_gaits=2)

    all_results_validation[name]['targets'].extend(val_t)
    all_results_validation[name]['preds'].extend(val_p)
    all_results_test[name]['targets'].extend(test_t)
    all_results_test[name]['preds'].extend(test_p)
    all_results_test[name]['subjects'].extend(test_pids)

    mae_val = mean_absolute_error(val_t, val_p)
    rmse_val = np.sqrt(mean_squared_error(val_t, val_p))
    r2_val = r2_score(val_t, val_p)
    print(f"Fold {k + 1:02d} | {name} | Validation: MAE={mae_val:.3f}, RMSE={rmse_val:.3f}, R2={r2_val:.3f}\n")

test_results_df = print_results(all_results_validation, all_results_test, models)
test_results_df

  0%|          | 0/30 [00:00<?, ?it/s]

Fold 1 | Validation Subs: ['1', '2', '3', '4', '5'] | Test Subs: ['6', '7', '8', '10', '11']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.1028 | Val MAE: 5.1855
[Epoch 200/1000] Train MAE: 0.7919 | Val MAE: 5.7597
Early stopping at epoch 219 (no improvement for 200 epochs)
Fold 01 | TCN | Validation: MAE=3.434, RMSE=3.578, R2=0.467

Fold 2 | Validation Subs: ['13', '14', '15', '17', '18'] | Test Subs: ['19', '20', '21', '22', '23']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.1009 | Val MAE: 3.9856
[Epoch 200/1000] Train MAE: 0.8184 | Val MAE: 3.9531
Early stopping at epoch 256 (no improvement for 200 epochs)
Fold 02 | TCN | Validation: MAE=2.661, RMSE=3.793, R2=-0.199

Fold 3 | Validation Subs: ['24', '25', '26', '27', '28'] | Test Subs: ['29', '30', '31', '32', '33']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.2275 | Val MAE: 3.8233
[Epoch 200/1000] Train MAE: 0.9543 | Val MAE: 3.8294
[Epoch 300/1000] Train MAE: 0.8233 | Val MAE: 3.1989
[Epoch 400/1000] Train MAE: 0.6754 | Val MAE: 3.1920
[Epoch 500/1000] Train MAE: 0.6035 | Val MAE: 3.1900
Early stopping at epoch 548 (no improvement for 200 epochs)
Fold 03 | TCN | Validation: MAE=2.729, RMSE=3.404, R2=0.436

Fold 4 | Validation Subs: ['34', '35', '36', '37', '38'] | Test Subs: ['40', '41', '42', '43', '45']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 0.9998 | Val MAE: 5.6863
[Epoch 200/1000] Train MAE: 0.7715 | Val MAE: 5.2931
Early stopping at epoch 224 (no improvement for 200 epochs)
Fold 04 | TCN | Validation: MAE=4.165, RMSE=4.589, R2=0.577

Fold 5 | Validation Subs: ['46', '47', '48', '49', '51'] | Test Subs: ['52', '53', '54', '55', '56']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 0.9826 | Val MAE: 2.6489
[Epoch 200/1000] Train MAE: 1.1720 | Val MAE: 3.1442
Early stopping at epoch 253 (no improvement for 200 epochs)
Fold 05 | TCN | Validation: MAE=1.901, RMSE=3.575, R2=0.582

Fold 6 | Validation Subs: ['57', '58', '59', '60', '61'] | Test Subs: ['62', '63', '64', '65', '66']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0289 | Val MAE: 2.3902
[Epoch 200/1000] Train MAE: 0.9992 | Val MAE: 1.3409
[Epoch 300/1000] Train MAE: 0.7801 | Val MAE: 1.8781
[Epoch 400/1000] Train MAE: 0.7548 | Val MAE: 1.6882
[Epoch 500/1000] Train MAE: 0.6166 | Val MAE: 1.1688
[Epoch 600/1000] Train MAE: 0.6050 | Val MAE: 1.5008
[Epoch 700/1000] Train MAE: 0.5805 | Val MAE: 1.3193
[Epoch 800/1000] Train MAE: 0.5625 | Val MAE: 1.1032
Early stopping at epoch 843 (no improvement for 200 epochs)
Fold 06 | TCN | Validation: MAE=0.631, RMSE=0.744, R2=0.000

Fold 7 | Validation Subs: ['67', '68', '69', '70', '71'] | Test Subs: ['72', '73', '74', '75', '76']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0163 | Val MAE: 3.8571
[Epoch 200/1000] Train MAE: 0.9793 | Val MAE: 3.2165
[Epoch 300/1000] Train MAE: 0.8257 | Val MAE: 2.8539
[Epoch 400/1000] Train MAE: 0.7448 | Val MAE: 3.5720
Early stopping at epoch 409 (no improvement for 200 epochs)
Fold 07 | TCN | Validation: MAE=1.743, RMSE=1.972, R2=0.000

Fold 8 | Validation Subs: ['77', '78', '79', '80', '81'] | Test Subs: ['82', '83', '84', '85', '86']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.1598 | Val MAE: 2.5500
[Epoch 200/1000] Train MAE: 0.9244 | Val MAE: 2.2841
Early stopping at epoch 248 (no improvement for 200 epochs)
Fold 08 | TCN | Validation: MAE=0.987, RMSE=1.491, R2=0.000

Fold 9 | Validation Subs: ['87', '88', '89', '90', '92'] | Test Subs: ['94', '95', '97', '98', '99']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0216 | Val MAE: 2.6564
[Epoch 200/1000] Train MAE: 0.8948 | Val MAE: 1.8649
Early stopping at epoch 220 (no improvement for 200 epochs)
Fold 09 | TCN | Validation: MAE=0.864, RMSE=1.018, R2=0.000

Fold 10 | Validation Subs: ['100', '102', '103', '105', '106'] | Test Subs: ['107', '109', '111', '112', '113']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.1034 | Val MAE: 4.8926
[Epoch 200/1000] Train MAE: 0.8439 | Val MAE: 3.4606
Early stopping at epoch 213 (no improvement for 200 epochs)
Fold 10 | TCN | Validation: MAE=2.421, RMSE=2.793, R2=0.000

Fold 11 | Validation Subs: ['115', '117', '118', '119', '120'] | Test Subs: ['121', '122', '123', '125', '126']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0203 | Val MAE: 3.0584
[Epoch 200/1000] Train MAE: 0.9115 | Val MAE: 1.1738
[Epoch 300/1000] Train MAE: 0.9414 | Val MAE: 1.4446
[Epoch 400/1000] Train MAE: 0.7355 | Val MAE: 1.5156
[Epoch 500/1000] Train MAE: 0.8042 | Val MAE: 1.4985
Early stopping at epoch 569 (no improvement for 200 epochs)
Fold 11 | TCN | Validation: MAE=0.451, RMSE=0.512, R2=0.000

Fold 12 | Validation Subs: ['127', '128', '129', '131', '133'] | Test Subs: ['134', '135', '136', '137', '138']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.1657 | Val MAE: 2.1012
[Epoch 200/1000] Train MAE: 0.8747 | Val MAE: 1.8429
[Epoch 300/1000] Train MAE: 1.0232 | Val MAE: 1.6217
[Epoch 400/1000] Train MAE: 0.8012 | Val MAE: 2.2714
Early stopping at epoch 499 (no improvement for 200 epochs)
Fold 12 | TCN | Validation: MAE=1.231, RMSE=1.541, R2=0.000

Fold 13 | Validation Subs: ['139', '140', '141', '142', '143'] | Test Subs: ['144', '145', '148', '149', '150']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.1378 | Val MAE: 4.3727
[Epoch 200/1000] Train MAE: 1.0311 | Val MAE: 3.1580
[Epoch 300/1000] Train MAE: 0.7909 | Val MAE: 3.5241
Early stopping at epoch 385 (no improvement for 200 epochs)
Fold 13 | TCN | Validation: MAE=1.501, RMSE=1.727, R2=0.000

Fold 14 | Validation Subs: ['151', '153', '154', '155', '156'] | Test Subs: ['157', '158', '159', '160', '162']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0344 | Val MAE: 3.0007
[Epoch 200/1000] Train MAE: 0.9486 | Val MAE: 3.0681
[Epoch 300/1000] Train MAE: 0.7216 | Val MAE: 2.3897
[Epoch 400/1000] Train MAE: 0.7888 | Val MAE: 2.6756
[Epoch 500/1000] Train MAE: 0.8043 | Val MAE: 2.8004
Early stopping at epoch 509 (no improvement for 200 epochs)
Fold 14 | TCN | Validation: MAE=2.038, RMSE=2.420, R2=0.000

Fold 15 | Validation Subs: ['164', '165', '167', '168', '171'] | Test Subs: ['173', '174', '175', '179', '180', '183', '184', '185', '187', '188']
Created 700 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.4648 | Val MAE: 3.0043
[Epoch 200/1000] Train MAE: 0.8508 | Val MAE: 3.7060
[Epoch 300/1000] Train MAE: 0.7817 | Val MAE: 3.4950
[Epoch 400/1000] Train MAE: 0.7949 | Val MAE: 3.4028
[Epoch 500/1000] Train MAE: 0.6376 | Val MAE: 3.1218
Early stopping at epoch 566 (no improvement for 200 epochs)
Fold 15 | TCN | Validation: MAE=2.394, RMSE=2.768, R2=0.000

Fold 16 | Validation Subs: ['6', '7', '8', '10', '11'] | Test Subs: ['1', '2', '3', '4', '5']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0062 | Val MAE: 4.2280
[Epoch 200/1000] Train MAE: 0.8818 | Val MAE: 3.6111
Early stopping at epoch 203 (no improvement for 200 epochs)
Fold 16 | TCN | Validation: MAE=3.012, RMSE=3.641, R2=0.370

Fold 17 | Validation Subs: ['19', '20', '21', '22', '23'] | Test Subs: ['13', '14', '15', '17', '18']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0575 | Val MAE: 5.2803
[Epoch 200/1000] Train MAE: 1.0761 | Val MAE: 5.0683
Early stopping at epoch 206 (no improvement for 200 epochs)
Fold 17 | TCN | Validation: MAE=4.573, RMSE=5.360, R2=-1.511

Fold 18 | Validation Subs: ['29', '30', '31', '32', '33'] | Test Subs: ['24', '25', '26', '27', '28']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 0.9317 | Val MAE: 5.2369
[Epoch 200/1000] Train MAE: 0.8874 | Val MAE: 6.0085
Early stopping at epoch 252 (no improvement for 200 epochs)
Fold 18 | TCN | Validation: MAE=4.430, RMSE=4.618, R2=0.417

Fold 19 | Validation Subs: ['40', '41', '42', '43', '45'] | Test Subs: ['34', '35', '36', '37', '38']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 0.9059 | Val MAE: 7.1867
[Epoch 200/1000] Train MAE: 0.8673 | Val MAE: 6.7940
[Epoch 300/1000] Train MAE: 0.8322 | Val MAE: 6.4742
Early stopping at epoch 333 (no improvement for 200 epochs)
Fold 19 | TCN | Validation: MAE=5.845, RMSE=8.604, R2=-0.335

Fold 20 | Validation Subs: ['52', '53', '54', '55', '56'] | Test Subs: ['46', '47', '48', '49', '51']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0803 | Val MAE: 2.2607
[Epoch 200/1000] Train MAE: 0.9411 | Val MAE: 0.5535
Early stopping at epoch 270 (no improvement for 200 epochs)
Fold 20 | TCN | Validation: MAE=0.392, RMSE=0.472, R2=0.000

Fold 21 | Validation Subs: ['62', '63', '64', '65', '66'] | Test Subs: ['57', '58', '59', '60', '61']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0272 | Val MAE: 3.0124
[Epoch 200/1000] Train MAE: 0.8847 | Val MAE: 2.4761
[Epoch 300/1000] Train MAE: 0.8044 | Val MAE: 2.4371
[Epoch 400/1000] Train MAE: 0.6699 | Val MAE: 2.6190
[Epoch 500/1000] Train MAE: 0.6473 | Val MAE: 2.3162
[Epoch 600/1000] Train MAE: 0.6755 | Val MAE: 2.3828
[Epoch 700/1000] Train MAE: 0.6250 | Val MAE: 2.2405
[Epoch 800/1000] Train MAE: 0.5498 | Val MAE: 2.4126
Early stopping at epoch 839 (no improvement for 200 epochs)
Fold 21 | TCN | Validation: MAE=1.801, RMSE=2.126, R2=0.000

Fold 22 | Validation Subs: ['72', '73', '74', '75', '76'] | Test Subs: ['67', '68', '69', '70', '71']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0066 | Val MAE: 3.6107
[Epoch 200/1000] Train MAE: 1.0960 | Val MAE: 3.2668
[Epoch 300/1000] Train MAE: 0.7421 | Val MAE: 3.6842
[Epoch 400/1000] Train MAE: 0.6974 | Val MAE: 3.4908
Early stopping at epoch 421 (no improvement for 200 epochs)
Fold 22 | TCN | Validation: MAE=2.350, RMSE=2.616, R2=0.000

Fold 23 | Validation Subs: ['82', '83', '84', '85', '86'] | Test Subs: ['77', '78', '79', '80', '81']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0854 | Val MAE: 2.3194
[Epoch 200/1000] Train MAE: 0.8622 | Val MAE: 0.8283
[Epoch 300/1000] Train MAE: 0.8929 | Val MAE: 2.1957
Early stopping at epoch 400 (no improvement for 200 epochs)
Fold 23 | TCN | Validation: MAE=0.828, RMSE=1.110, R2=0.000

Fold 24 | Validation Subs: ['94', '95', '97', '98', '99'] | Test Subs: ['87', '88', '89', '90', '92']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 0.9989 | Val MAE: 3.3698
[Epoch 200/1000] Train MAE: 0.9262 | Val MAE: 3.1011
[Epoch 300/1000] Train MAE: 0.8666 | Val MAE: 3.8069
Early stopping at epoch 351 (no improvement for 200 epochs)
Fold 24 | TCN | Validation: MAE=1.500, RMSE=1.606, R2=0.000

Fold 25 | Validation Subs: ['107', '109', '111', '112', '113'] | Test Subs: ['100', '102', '103', '105', '106']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 0.9744 | Val MAE: 2.4500
[Epoch 200/1000] Train MAE: 0.8441 | Val MAE: 1.8009
[Epoch 300/1000] Train MAE: 1.0888 | Val MAE: 2.7372
[Epoch 400/1000] Train MAE: 0.7275 | Val MAE: 1.6044
Early stopping at epoch 442 (no improvement for 200 epochs)
Fold 25 | TCN | Validation: MAE=0.978, RMSE=1.073, R2=0.000

Fold 26 | Validation Subs: ['121', '122', '123', '125', '126'] | Test Subs: ['115', '117', '118', '119', '120']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0732 | Val MAE: 1.9254
[Epoch 200/1000] Train MAE: 0.8243 | Val MAE: 2.2215
[Epoch 300/1000] Train MAE: 0.7866 | Val MAE: 1.3861
Early stopping at epoch 379 (no improvement for 200 epochs)
Fold 26 | TCN | Validation: MAE=0.473, RMSE=0.550, R2=0.000

Fold 27 | Validation Subs: ['134', '135', '136', '137', '138'] | Test Subs: ['127', '128', '129', '131', '133']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 0.9388 | Val MAE: 2.1198
[Epoch 200/1000] Train MAE: 0.8797 | Val MAE: 3.0176
[Epoch 300/1000] Train MAE: 0.8100 | Val MAE: 2.5507
[Epoch 400/1000] Train MAE: 0.7725 | Val MAE: 2.0890
[Epoch 500/1000] Train MAE: 0.6172 | Val MAE: 2.3532
[Epoch 600/1000] Train MAE: 0.6770 | Val MAE: 1.9841
[Epoch 700/1000] Train MAE: 0.5983 | Val MAE: 2.2273
Early stopping at epoch 713 (no improvement for 200 epochs)
Fold 27 | TCN | Validation: MAE=1.624, RMSE=2.039, R2=0.000

Fold 28 | Validation Subs: ['144', '145', '148', '149', '150'] | Test Subs: ['139', '140', '141', '142', '143']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.2045 | Val MAE: 1.0766
[Epoch 200/1000] Train MAE: 0.9138 | Val MAE: 1.7185
Early stopping at epoch 291 (no improvement for 200 epochs)
Fold 28 | TCN | Validation: MAE=0.602, RMSE=0.794, R2=0.000

Fold 29 | Validation Subs: ['157', '158', '159', '160', '162'] | Test Subs: ['151', '153', '154', '155', '156']
Created 725 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.0265 | Val MAE: 2.4496
[Epoch 200/1000] Train MAE: 0.9259 | Val MAE: 2.6150
[Epoch 300/1000] Train MAE: 0.7867 | Val MAE: 1.9439
[Epoch 400/1000] Train MAE: 0.7264 | Val MAE: 1.9177
Early stopping at epoch 424 (no improvement for 200 epochs)
Fold 29 | TCN | Validation: MAE=1.377, RMSE=1.690, R2=0.000

Fold 30 | Validation Subs: ['173', '174', '175', '179', '180', '183', '184', '185', '187', '188'] | Test Subs: ['164', '165', '167', '168', '171']
Created 700 gait windows
Starting training...
[Epoch 100/1000] Train MAE: 1.1413 | Val MAE: 3.4984
[Epoch 200/1000] Train MAE: 0.8125 | Val MAE: 2.8931
Early stopping at epoch 245 (no improvement for 200 epochs)
Fold 30 | TCN | Validation: MAE=2.145, RMSE=2.441, R2=0.000


=== Validation Performance (across all folds) ===
          MAE      RMSE        R2  Pearson r     Pearson p
TCN  2.039582  3.010726  0.703184   0.864066  1.824989e-47

=== Test Performance (across all folds) ===

          MAE      RMSE        R2  Pearson r     Pearson p
TCN  2.661349  3.824711  0.520993   0.786189  8.537867e-34

In [8]:
from ci import *

ci_results = {}

name = "TCN"

ci_results[name] = subject_bootstrap_ci(
    all_results_test[name]['targets'],
    all_results_test[name]['preds'],
    all_results_test[name]['subjects'])

pd.DataFrame(ci_results['TCN'])

                 MAE            RMSE              R2       Pearson r
mean        2.661349        3.824711        0.520993        0.786189
ci    [2.334, 2.983]  [3.212, 4.302]  [0.301, 0.674]  [0.729, 0.849]

## Loading Lesion Left Classifcation Data

In [6]:
save_dir = 'data_clf'
loaded_dir = 'csv_clf'
preprocess_and_save_data(loaded_dir, save_dir)
all_files = filter_valid_files(os.listdir(loaded_dir))
participant_ids = sorted({re.search(r'ID(\d+)_', f).group(1) for f in all_files}, key=lambda x: int(x))

Global Average Loaded Gait Length: 100
Preprocessed data saved to data_clf

## Classification Evaluation Function

In [9]:
def evaluate_model_clf(model, test_loader, n_select_gaits, num_classes=3):
    """Classification evaluation: aggregate unit-level predictions per participant (majority vote)."""
    model.eval()
    device = next(model.parameters()).device

    t = []
    p = []

    with torch.no_grad():
        for batch in test_loader:
            if len(batch) == 3:
                x_load_list, y_batch, _ = batch
            else:
                x_load_list, y_batch = batch

            for i, x_load_sample in enumerate(x_load_list):
                x_task = x_load_sample[:6]
                num_units = len(x_task) - n_select_gaits + 1

                unit_preds = []

                for start_idx in range(num_units):
                    unit = x_task[start_idx:start_idx + n_select_gaits]
                    unit_tensor = unit.unsqueeze(0).to(device)

                    logits = model(unit_tensor)
                    pred_class = logits.argmax(dim=1).item()
                    unit_preds.append(pred_class)

                participant_target = y_batch[i].item()
                participant_pred = int(np.bincount(unit_preds).argmax())

                t.append(participant_target)
                p.append(participant_pred)

    return t, p

## Classification Model Training Function

In [11]:
def train_model_clf(model, train_loader, experiment_seed=42, num_epochs=1000, N_gaits=2, val_loader=None, patience=50, num_classes=3):
    set_deterministic(experiment_seed)
    random.seed(experiment_seed)
    np.random.seed(experiment_seed)

    all_x = []
    all_y = []

    for batch in train_loader:
        if len(batch) == 3:
            x_load_list, y_batch, _ = batch
        else:
            x_load_list, y_batch = batch
        all_x.extend(x_load_list)
        all_y.extend(y_batch)

    optimized_train_loader = create_gait_units_dataloader(all_x, all_y, N_gaits=N_gaits,
                                                          batch_size=bsize, shuffle=True)

    val_unit_loader = None
    if val_loader is not None:
        val_x, val_y = [], []
        for batch in val_loader:
            if len(batch) == 3:
                x_load_list, y_batch, _ = batch
            else:
                x_load_list, y_batch = batch
            val_x.extend(x_load_list)
            val_y.extend(y_batch)
        val_unit_loader = create_gait_units_dataloader(val_x, val_y, N_gaits=N_gaits,
                                                       batch_size=bsize, shuffle=False)

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs)

    best_val_loss = float('inf')
    best_state = None
    epochs_no_improve = 0

    print("Starting training...")
    for epoch in range(num_epochs):
        model.train()
        total_loss = 0

        for x_batch, y_batch in optimized_train_loader:
            x_batch = x_batch.to(device)
            y_batch = y_batch.to(device).long()

            logits = model(x_batch)
            loss = F.cross_entropy(logits, y_batch)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        scheduler.step()

        if val_unit_loader is not None:
            model.eval()
            val_loss_sum, val_n = 0.0, 0
            with torch.no_grad():
                for x_batch, y_batch in val_unit_loader:
                    x_batch = x_batch.to(device)
                    y_batch = y_batch.to(device).long()
                    logits = model(x_batch)
                    val_loss_sum += F.cross_entropy(logits, y_batch, reduction='sum').item()
                    val_n += x_batch.size(0)
            val_loss = val_loss_sum / val_n
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                epochs_no_improve = 0
            else:
                epochs_no_improve += 1
            if epochs_no_improve >= patience:
                print(f"Early stopping at epoch {epoch + 1} (no improvement for {patience} epochs)")
                if best_state is not None:
                    model.load_state_dict(best_state)
                break

        if (epoch + 1) % 100 == 0:
            avg_loss = total_loss / len(optimized_train_loader)
            msg = f"[Epoch {epoch + 1}/{num_epochs}] Train CE loss: {avg_loss:.4f}"
            if val_unit_loader is not None:
                val_t, val_p = evaluate_model_clf(model, val_loader, n_select_gaits=N_gaits, num_classes=num_classes)
                val_acc = np.mean(np.array(val_t) == np.array(val_p))
                msg += f" | Val CE loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}"
            print(msg)

    if val_loader is not None and best_state is not None:
        model.load_state_dict(best_state)
    return model

## TCN Classification Training

In [17]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from val_test import val_test

n_folds = 30
models_clf = {'TCN': []}
name = list(models_clf.keys())[0]

all_results_validation_clf = {name: {'targets': [], 'preds': []}}
all_results_test_clf = {name: {'targets': [], 'preds': [], 'subjects': []}}

for k in tqdm(range(n_folds)):

    model = TCN(N_gaits=2, output_dim=3).to(device)  # 3-class logits

    validation_pids, test_pids = val_test(participant_ids, k)
    print(f"Fold {k+1} | Validation Subs: {validation_pids} | Test Subs: {test_pids}")

    train_loader, val_loader, test_loader = cv_data_create(validation_pids, test_pids, save_dir, batch_size=bsize)
    trained_model = train_model_clf(model, train_loader, experiment_seed=k, num_epochs=1000, N_gaits=2,
                                    val_loader=val_loader, patience=150, num_classes=3)

    val_t, val_p = evaluate_model_clf(trained_model, val_loader, n_select_gaits=2, num_classes=3)
    test_t, test_p = evaluate_model_clf(trained_model, test_loader, n_select_gaits=2, num_classes=3)

    all_results_validation_clf[name]['targets'].extend(val_t)
    all_results_validation_clf[name]['preds'].extend(val_p)

    all_results_test_clf[name]['targets'].extend(test_t)
    all_results_test_clf[name]['preds'].extend(test_p)
    all_results_test_clf[name]['subjects'].extend(test_pids)

    acc_val = accuracy_score(val_t, val_p)
    f1m_val = f1_score(val_t, val_p, average='macro')
    print(f"Fold {k + 1:02d} | {name} | Validation: Acc={acc_val:.3f}, F1-macro={f1m_val:.3f}\n")

# Overall pooled (OOF) metrics across all folds
val_t_all = np.array(all_results_validation_clf[name]['targets'])
val_p_all = np.array(all_results_validation_clf[name]['preds'])
test_t_all = np.array(all_results_test_clf[name]['targets'])
test_p_all = np.array(all_results_test_clf[name]['preds'])

def classification_metrics(t, p):
    return {
        'Accuracy': accuracy_score(t, p),
        'F1 (weighted)': f1_score(t, p, average='weighted'),
        'F1 (macro)': f1_score(t, p, average='macro'),
        'Precision (weighted)': precision_score(t, p, average='weighted', zero_division=0),
        'Precision (macro)': precision_score(t, p, average='macro', zero_division=0),
        'Recall (weighted)': recall_score(t, p, average='weighted', zero_division=0),
        'Recall (macro)': recall_score(t, p, average='macro', zero_division=0),
    }

results_val = classification_metrics(val_t_all, val_p_all)
results_test = classification_metrics(test_t_all, test_p_all)

print("\n=== Validation Performance (across all folds) ===")
print(pd.DataFrame({name: results_val}).T)

print("\n=== Test Performance (across all folds) ===")
results_test_df = pd.DataFrame({name: results_test}).T
results_test_df

  0%|          | 0/30 [00:00<?, ?it/s]

Fold 1 | Validation Subs: ['1', '2', '3', '4', '5'] | Test Subs: ['6', '7', '8', '10', '11']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0001 | Val CE loss: 4.4859 | Val Acc: 0.6000
Early stopping at epoch 151 (no improvement for 150 epochs)
Fold 01 | TCN | Validation: Acc=0.000, F1-macro=0.000

Fold 2 | Validation Subs: ['13', '14', '15', '17', '18'] | Test Subs: ['19', '20', '21', '22', '23']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0008 | Val CE loss: 5.4416 | Val Acc: 0.6000
Early stopping at epoch 153 (no improvement for 150 epochs)
Fold 02 | TCN | Validation: Acc=0.600, F1-macro=0.375

Fold 3 | Validation Subs: ['24', '25', '26', '27', '28'] | Test Subs: ['29', '30', '31', '32', '33']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0004 | Val CE loss: 3.1203 | Val Acc: 0.6000
Early stopping at epoch 165 (no improvement for 150 epochs)
Fold 03 | TCN | Validation: Acc=0.600, F1-macro=0.583

Fold 4 | Validation Subs: ['34', '35', '36', '37', '38'] | Test Subs: ['40', '41', '42', '43', '45']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0129 | Val CE loss: 0.9289 | Val Acc: 0.8000
Early stopping at epoch 162 (no improvement for 150 epochs)
Fold 04 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 5 | Validation Subs: ['46', '47', '48', '49', '51'] | Test Subs: ['52', '53', '54', '55', '56']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0268 | Val CE loss: 0.2138 | Val Acc: 0.8000
[Epoch 200/1000] Train CE loss: 0.0002 | Val CE loss: 0.2733 | Val Acc: 1.0000
Early stopping at epoch 298 (no improvement for 150 epochs)
Fold 05 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 6 | Validation Subs: ['57', '58', '59', '60', '61'] | Test Subs: ['62', '63', '64', '65', '66']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0046 | Val CE loss: 0.0008 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0001 | Val CE loss: 0.0017 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0021 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0000 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0001 | Val CE loss: 0.0026 | Val Acc: 1.0000
Early stopping at epoch 588 (no improvement for 150 epochs)
Fold 06 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 7 | Validation Subs: ['67', '68', '69', '70', '71'] | Test Subs: ['72', '73', '74', '75', '76']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0106 | Val CE loss: 0.0001 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0006 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0000 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0001 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 429 (no improvement for 150 epochs)
Fold 07 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 8 | Validation Subs: ['77', '78', '79', '80', '81'] | Test Subs: ['82', '83', '84', '85', '86']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0434 | Val CE loss: 0.0304 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0001 | Val CE loss: 0.0001 | Val Acc: 1.0000
Early stopping at epoch 240 (no improvement for 150 epochs)
Fold 08 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 9 | Validation Subs: ['87', '88', '89', '90', '92'] | Test Subs: ['94', '95', '97', '98', '99']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0003 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0001 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0000 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0000 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 500/1000] Train CE loss: 0.0000 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 520 (no improvement for 150 epochs)
Fold 09 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 10 | Validation Subs: ['100', '102', '103', '105', '106'] | Test Subs: ['107', '109', '111', '112', '113']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0018 | Val CE loss: 0.4151 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0001 | Val CE loss: 0.4228 | Val Acc: 1.0000
Early stopping at epoch 265 (no improvement for 150 epochs)
Fold 10 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 11 | Validation Subs: ['115', '117', '118', '119', '120'] | Test Subs: ['121', '122', '123', '125', '126']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0003 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0031 | Val CE loss: 0.0001 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0000 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 377 (no improvement for 150 epochs)
Fold 11 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 12 | Validation Subs: ['127', '128', '129', '131', '133'] | Test Subs: ['134', '135', '136', '137', '138']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0001 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0292 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0001 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 350 (no improvement for 150 epochs)
Fold 12 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 13 | Validation Subs: ['139', '140', '141', '142', '143'] | Test Subs: ['144', '145', '148', '149', '150']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0002 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0003 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0000 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 353 (no improvement for 150 epochs)
Fold 13 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 14 | Validation Subs: ['151', '153', '154', '155', '156'] | Test Subs: ['157', '158', '159', '160', '162']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0005 | Val CE loss: 0.0445 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0002 | Val CE loss: 0.0327 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0001 | Val CE loss: 0.0196 | Val Acc: 1.0000
Early stopping at epoch 389 (no improvement for 150 epochs)
Fold 14 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 15 | Validation Subs: ['164', '165', '167', '168', '171'] | Test Subs: ['173', '174', '175', '179', '180', '183', '184', '185', '187', '188']
Created 700 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0003 | Val CE loss: 0.0001 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0000 | Val CE loss: 0.0001 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0000 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 364 (no improvement for 150 epochs)
Fold 15 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 16 | Validation Subs: ['6', '7', '8', '10', '11'] | Test Subs: ['1', '2', '3', '4', '5']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0001 | Val CE loss: 4.1679 | Val Acc: 0.4000
Early stopping at epoch 152 (no improvement for 150 epochs)
Fold 16 | TCN | Validation: Acc=0.800, F1-macro=0.444

Fold 17 | Validation Subs: ['19', '20', '21', '22', '23'] | Test Subs: ['13', '14', '15', '17', '18']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0004 | Val CE loss: 3.5425 | Val Acc: 0.4000
Early stopping at epoch 152 (no improvement for 150 epochs)
Fold 17 | TCN | Validation: Acc=0.400, F1-macro=0.267

Fold 18 | Validation Subs: ['29', '30', '31', '32', '33'] | Test Subs: ['24', '25', '26', '27', '28']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0002 | Val CE loss: 1.7802 | Val Acc: 0.4000
Early stopping at epoch 166 (no improvement for 150 epochs)
Fold 18 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 19 | Validation Subs: ['40', '41', '42', '43', '45'] | Test Subs: ['34', '35', '36', '37', '38']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0005 | Val CE loss: 4.2426 | Val Acc: 0.6000
Early stopping at epoch 151 (no improvement for 150 epochs)
Fold 19 | TCN | Validation: Acc=0.800, F1-macro=0.444

Fold 20 | Validation Subs: ['52', '53', '54', '55', '56'] | Test Subs: ['46', '47', '48', '49', '51']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0009 | Val CE loss: 0.0010 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0103 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 258 (no improvement for 150 epochs)
Fold 20 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 21 | Validation Subs: ['62', '63', '64', '65', '66'] | Test Subs: ['57', '58', '59', '60', '61']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0002 | Val CE loss: 0.4351 | Val Acc: 0.8000
[Epoch 200/1000] Train CE loss: 0.0031 | Val CE loss: 0.1104 | Val Acc: 1.0000
Early stopping at epoch 207 (no improvement for 150 epochs)
Fold 21 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 22 | Validation Subs: ['72', '73', '74', '75', '76'] | Test Subs: ['67', '68', '69', '70', '71']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0271 | Val CE loss: 0.2741 | Val Acc: 0.8000
Early stopping at epoch 178 (no improvement for 150 epochs)
Fold 22 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 23 | Validation Subs: ['82', '83', '84', '85', '86'] | Test Subs: ['77', '78', '79', '80', '81']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0003 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0002 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0001 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 400/1000] Train CE loss: 0.0000 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 493 (no improvement for 150 epochs)
Fold 23 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 24 | Validation Subs: ['94', '95', '97', '98', '99'] | Test Subs: ['87', '88', '89', '90', '92']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0018 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 194 (no improvement for 150 epochs)
Fold 24 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 25 | Validation Subs: ['107', '109', '111', '112', '113'] | Test Subs: ['100', '102', '103', '105', '106']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0002 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0011 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 261 (no improvement for 150 epochs)
Fold 25 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 26 | Validation Subs: ['121', '122', '123', '125', '126'] | Test Subs: ['115', '117', '118', '119', '120']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0183 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 187 (no improvement for 150 epochs)
Fold 26 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 27 | Validation Subs: ['134', '135', '136', '137', '138'] | Test Subs: ['127', '128', '129', '131', '133']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0016 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0001 | Val CE loss: 0.0001 | Val Acc: 1.0000
Early stopping at epoch 277 (no improvement for 150 epochs)
Fold 27 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 28 | Validation Subs: ['144', '145', '148', '149', '150'] | Test Subs: ['139', '140', '141', '142', '143']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0003 | Val CE loss: 0.0000 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0001 | Val CE loss: 0.0000 | Val Acc: 1.0000
Early stopping at epoch 278 (no improvement for 150 epochs)
Fold 28 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 29 | Validation Subs: ['157', '158', '159', '160', '162'] | Test Subs: ['151', '153', '154', '155', '156']
Created 725 gait windows
Created 25 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0003 | Val CE loss: 0.8363 | Val Acc: 0.8000
[Epoch 200/1000] Train CE loss: 0.0003 | Val CE loss: 0.0588 | Val Acc: 1.0000
[Epoch 300/1000] Train CE loss: 0.0001 | Val CE loss: 0.1137 | Val Acc: 1.0000
Early stopping at epoch 324 (no improvement for 150 epochs)
Fold 29 | TCN | Validation: Acc=1.000, F1-macro=1.000

Fold 30 | Validation Subs: ['173', '174', '175', '179', '180', '183', '184', '185', '187', '188'] | Test Subs: ['164', '165', '167', '168', '171']
Created 700 gait windows
Created 50 gait windows
Starting training...
[Epoch 100/1000] Train CE loss: 0.0231 | Val CE loss: 0.3110 | Val Acc: 1.0000
[Epoch 200/1000] Train CE loss: 0.0001 | Val CE loss: 0.4473 | Val Acc: 0.9000
Early stopping at epoch 255 (no improvement for 150 epochs)
Fold 30 | TCN | Validation: Acc=1.000, F1-macro=1.000


=== Validation Performance (across all folds) ===
     Accuracy  F1 (weighted)  F1 (macro)  Precision (weighted)  \
TCN  0.909677       0.898046    0.763035              0.905003

     Precision (macro)  Recall (weighted)  Recall (macro)
TCN           0.860154           0.909677        0.730159

=== Test Performance (across all folds) ===

,Accuracy,F1 (weighted),F1 (macro),Precision (weighted),Precision (macro),Recall (weighted),Recall (macro)
TCN,0.858065,0.839166,0.637356,0.833443,0.698642,0.858065,0.615873

In [18]:
from ci_class import subject_bootstrap_ci_class

ci_results = {}

name = "TCN"

ci_results[name] = subject_bootstrap_ci_class(
    all_results_test_clf[name]['targets'],
    all_results_test_clf[name]['preds'],
    all_results_test_clf[name]['subjects'])

pd.DataFrame(ci_results['TCN'])

,Accuracy,F1 (weighted),F1 (macro),Precision (weighted),Precision (macro),Recall (weighted),Recall (macro)
mean,0.858065,0.839166,0.637356,0.833443,0.698642,0.858065,0.615873
ci,"[0.814, 0.902]","[0.788, 0.891]","[0.533, 0.719]","[0.776, 0.896]","[0.529, 0.865]","[0.814, 0.902]","[0.537, 0.689]"